// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RENAME_USER = 'RENAME_USER';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

// Dashboard
export const DASHBOARD_LISTS_GET = 'DASHBOARD_LISTS_GET';
export const DASHBAORD_DATA_ERROR = 'DASHBAORD_DATA_ERROR';
export const DASHBOARD_SET_FILTERS = 'DASHBOARD_SET_FILTERS';

//Invites
export const INVITE_PENDING = 'INVITE_PENDING';
export const INVITE_ACCEPTED = 'INVITE_ACCEPTED';
export const INVITE_ERROR = 'INVITE_ERROR';
export const INVITE_RESET_ERROR = 'INVITE_RESET_ERROR';
export const INVITE_CLEAR = 'INVITE_CLEAR';
export const INVITE_TOKEN_ERROR = 'INVITE_TOKEN_ERROR';
export const INVITE_CONVERT_TOKEN_ERROR = 'INVITE_RESET_TOKEN_ERROR';

// Lists
export const CURRENT_LIST_GET = 'CURRENT_LIST_GET';
export const PARENT_LIST_GET = 'PARENT_LIST_GET';
export const LOAD_LIST_PERMISSIONS = 'LOAD_LIST_PERMISSIONS';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
export const LIST_RESET = 'LIST_RESET';
export const NEW_LIST_ITEM = 'NEW_LIST_ITEM';
export const MODIFY_LIST_ITEM = 'MODIFY_LIST_ITEM';
export const SELECT_LIST_ITEM = 'SELECT_LIST_ITEM';
export const RENAME_LIST = 'RENAME_LIST';
export const LEAVE_LIST = 'LEAVE_LIST';
export const DELETE_LIST = 'DELETE_LIST';

// Alerts
export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
